<?php

	acf_add_local_field_group(array(
		'key' => 'group_6269d4b37722f',
		'title' => 'Blocks - Map',
		'fields' => array(
			array(
				'key' => 'field_6269d4cdb3dd6',
				'label' => 'Map Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => 'What is this a map for, eg. Centre for Stories office',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Centre for Stories Office',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6269d63b088b0',
				'label' => 'Map Link',
				'name' => 'map_link',
				'type' => 'url',
				'instructions' => 'Google maps directions page, defaults to Centre for Stories office',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'https://www.google.com/maps/dir//Centre+for+Stories,+100+Aberdeen+St,+Northbridge+WA+6003/@-31.946072,115.8563453,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x2a32bad1f13f242d:0x72f649424cf0be64!2m2!1d115.8584928!2d-31.946139',
				'placeholder' => '',
			),
			array(
				'key' => 'field_6269deb836000',
				'label' => 'Show Pin',
				'name' => 'show_pin',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6269d6d9088b1',
				'label' => 'Map',
				'name' => 'map',
				'type' => 'google_map',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '-31.946072',
				'center_lng' => '115.8563453',
				'zoom' => 14,
				'height' => 400,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/map-block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

?>